nn_config:
  name: NeuralNet
  learning_rates: [0.0001, 0.001]
  batch_size: [128, 512]
  epochs: [5, 10, 50]
  layers: [[10], [20, 10, 5], [20, 15, 10, 5]]
  dpg: False

auto_config:
  name: Autoencoder
  learning_rates: [0.0001, 0.001]
  batch_size: [128, 512]
  epochs: [5, 10, 50]
  layers: [[15, 5], [25, 20, 15, 10, 5], [25, 20, 15], [20, 10, 5]]

lg_config:
  name: Logistic
  solver : ["newton-cg", "lbfgs", "saga"]
  penalty : ["none", "l2"]
  C : [0.1, 1, 10, 100]
  max_iter : [1, 10, 100]